apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fiap
resources:
  - secret/blog-db.yml
  - config-map/blog-app.yml
  - pvc/blog-db.yml
  - deployment/blog-db.yml
  - service/blog-db.yml
  - deployment/blog-app.yml
  - service/blog-db.yml
  - route/blog-app.yml
  - hpa/blog-app.yml
